// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: settings.proto

package io.github.cyborgnoodle;

public final class Settings {
  private Settings() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SettingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Setting)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool xp_gain = 100;</code>
     */
    boolean getXpGain();

    /**
     * <code>optional int32 xp_msg_max = 101;</code>
     */
    int getXpMsgMax();

    /**
     * <code>optional int32 xp_msg_min = 102;</code>
     */
    int getXpMsgMin();

    /**
     * <code>optional int32 xp_bomb_max = 103;</code>
     */
    int getXpBombMax();

    /**
     * <code>optional int32 xp_bomb_min = 104;</code>
     */
    int getXpBombMin();

    /**
     * <code>optional int32 xp_bomb_timeout_max = 105;</code>
     */
    int getXpBombTimeoutMax();

    /**
     * <code>optional int32 xp_bomb_timeout_min = 106;</code>
     */
    int getXpBombTimeoutMin();

    /**
     * <code>optional bool chat_comment_edits = 200;</code>
     */
    boolean getChatCommentEdits();

    /**
     * <code>optional bool chat_comment_badwords = 201;</code>
     */
    boolean getChatCommentBadwords();

    /**
     * <code>optional bool chat_comment_newuser = 202;</code>
     */
    boolean getChatCommentNewuser();

    /**
     * <code>optional bool chat_comment_banuser = 203;</code>
     */
    boolean getChatCommentBanuser();

    /**
     * <code>optional bool chat_comment_leaveuser = 204;</code>
     */
    boolean getChatCommentLeaveuser();

    /**
     * <code>optional int32 chat_comment_edits_chance = 205;</code>
     */
    int getChatCommentEditsChance();

    /**
     * <code>optional bool autoconv_enable = 300;</code>
     */
    boolean getAutoconvEnable();

    /**
     * <code>optional bool autoconv_time = 301;</code>
     */
    boolean getAutoconvTime();

    /**
     * <code>optional bool autoconv_temperature = 302;</code>
     */
    boolean getAutoconvTemperature();

    /**
     * <code>optional bool autoconv_length = 303;</code>
     */
    boolean getAutoconvLength();

    /**
     * <code>optional bool autoconv_area = 304;</code>
     */
    boolean getAutoconvArea();

    /**
     * <code>optional bool autoconv_volume = 305;</code>
     */
    boolean getAutoconvVolume();

    /**
     * <code>optional bool autoconv_mass = 306;</code>
     */
    boolean getAutoconvMass();

    /**
     * <code>optional bool autoconv_currency = 307;</code>
     */
    boolean getAutoconvCurrency();

    /**
     * <code>optional bool misc_addemoji = 400;</code>
     */
    boolean getMiscAddemoji();

    /**
     * <code>repeated int32 markov_exluded_channels = 500;</code>
     */
    java.util.List<java.lang.Integer> getMarkovExludedChannelsList();
    /**
     * <code>repeated int32 markov_exluded_channels = 500;</code>
     */
    int getMarkovExludedChannelsCount();
    /**
     * <code>repeated int32 markov_exluded_channels = 500;</code>
     */
    int getMarkovExludedChannels(int index);
  }
  /**
   * Protobuf type {@code Setting}
   */
  public  static final class Setting extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Setting)
      SettingOrBuilder {
    // Use Setting.newBuilder() to construct.
    private Setting(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Setting() {
      xpGain_ = false;
      xpMsgMax_ = 0;
      xpMsgMin_ = 0;
      xpBombMax_ = 0;
      xpBombMin_ = 0;
      xpBombTimeoutMax_ = 0;
      xpBombTimeoutMin_ = 0;
      chatCommentEdits_ = false;
      chatCommentBadwords_ = false;
      chatCommentNewuser_ = false;
      chatCommentBanuser_ = false;
      chatCommentLeaveuser_ = false;
      chatCommentEditsChance_ = 0;
      autoconvEnable_ = false;
      autoconvTime_ = false;
      autoconvTemperature_ = false;
      autoconvLength_ = false;
      autoconvArea_ = false;
      autoconvVolume_ = false;
      autoconvMass_ = false;
      autoconvCurrency_ = false;
      miscAddemoji_ = false;
      markovExludedChannels_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Setting(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 800: {

              xpGain_ = input.readBool();
              break;
            }
            case 808: {

              xpMsgMax_ = input.readInt32();
              break;
            }
            case 816: {

              xpMsgMin_ = input.readInt32();
              break;
            }
            case 824: {

              xpBombMax_ = input.readInt32();
              break;
            }
            case 832: {

              xpBombMin_ = input.readInt32();
              break;
            }
            case 840: {

              xpBombTimeoutMax_ = input.readInt32();
              break;
            }
            case 848: {

              xpBombTimeoutMin_ = input.readInt32();
              break;
            }
            case 1600: {

              chatCommentEdits_ = input.readBool();
              break;
            }
            case 1608: {

              chatCommentBadwords_ = input.readBool();
              break;
            }
            case 1616: {

              chatCommentNewuser_ = input.readBool();
              break;
            }
            case 1624: {

              chatCommentBanuser_ = input.readBool();
              break;
            }
            case 1632: {

              chatCommentLeaveuser_ = input.readBool();
              break;
            }
            case 1640: {

              chatCommentEditsChance_ = input.readInt32();
              break;
            }
            case 2400: {

              autoconvEnable_ = input.readBool();
              break;
            }
            case 2408: {

              autoconvTime_ = input.readBool();
              break;
            }
            case 2416: {

              autoconvTemperature_ = input.readBool();
              break;
            }
            case 2424: {

              autoconvLength_ = input.readBool();
              break;
            }
            case 2432: {

              autoconvArea_ = input.readBool();
              break;
            }
            case 2440: {

              autoconvVolume_ = input.readBool();
              break;
            }
            case 2448: {

              autoconvMass_ = input.readBool();
              break;
            }
            case 2456: {

              autoconvCurrency_ = input.readBool();
              break;
            }
            case 3200: {

              miscAddemoji_ = input.readBool();
              break;
            }
            case 4000: {
              if (!((mutable_bitField0_ & 0x00400000) == 0x00400000)) {
                markovExludedChannels_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00400000;
              }
              markovExludedChannels_.add(input.readInt32());
              break;
            }
            case 4002: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00400000) == 0x00400000) && input.getBytesUntilLimit() > 0) {
                markovExludedChannels_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00400000;
              }
              while (input.getBytesUntilLimit() > 0) {
                markovExludedChannels_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00400000) == 0x00400000)) {
          markovExludedChannels_ = java.util.Collections.unmodifiableList(markovExludedChannels_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.cyborgnoodle.Settings.internal_static_Setting_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.cyborgnoodle.Settings.internal_static_Setting_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.cyborgnoodle.Settings.Setting.class, io.github.cyborgnoodle.Settings.Setting.Builder.class);
    }

    private int bitField0_;
    public static final int XP_GAIN_FIELD_NUMBER = 100;
    private boolean xpGain_;
    /**
     * <code>optional bool xp_gain = 100;</code>
     */
    public boolean getXpGain() {
      return xpGain_;
    }

    public static final int XP_MSG_MAX_FIELD_NUMBER = 101;
    private int xpMsgMax_;
    /**
     * <code>optional int32 xp_msg_max = 101;</code>
     */
    public int getXpMsgMax() {
      return xpMsgMax_;
    }

    public static final int XP_MSG_MIN_FIELD_NUMBER = 102;
    private int xpMsgMin_;
    /**
     * <code>optional int32 xp_msg_min = 102;</code>
     */
    public int getXpMsgMin() {
      return xpMsgMin_;
    }

    public static final int XP_BOMB_MAX_FIELD_NUMBER = 103;
    private int xpBombMax_;
    /**
     * <code>optional int32 xp_bomb_max = 103;</code>
     */
    public int getXpBombMax() {
      return xpBombMax_;
    }

    public static final int XP_BOMB_MIN_FIELD_NUMBER = 104;
    private int xpBombMin_;
    /**
     * <code>optional int32 xp_bomb_min = 104;</code>
     */
    public int getXpBombMin() {
      return xpBombMin_;
    }

    public static final int XP_BOMB_TIMEOUT_MAX_FIELD_NUMBER = 105;
    private int xpBombTimeoutMax_;
    /**
     * <code>optional int32 xp_bomb_timeout_max = 105;</code>
     */
    public int getXpBombTimeoutMax() {
      return xpBombTimeoutMax_;
    }

    public static final int XP_BOMB_TIMEOUT_MIN_FIELD_NUMBER = 106;
    private int xpBombTimeoutMin_;
    /**
     * <code>optional int32 xp_bomb_timeout_min = 106;</code>
     */
    public int getXpBombTimeoutMin() {
      return xpBombTimeoutMin_;
    }

    public static final int CHAT_COMMENT_EDITS_FIELD_NUMBER = 200;
    private boolean chatCommentEdits_;
    /**
     * <code>optional bool chat_comment_edits = 200;</code>
     */
    public boolean getChatCommentEdits() {
      return chatCommentEdits_;
    }

    public static final int CHAT_COMMENT_BADWORDS_FIELD_NUMBER = 201;
    private boolean chatCommentBadwords_;
    /**
     * <code>optional bool chat_comment_badwords = 201;</code>
     */
    public boolean getChatCommentBadwords() {
      return chatCommentBadwords_;
    }

    public static final int CHAT_COMMENT_NEWUSER_FIELD_NUMBER = 202;
    private boolean chatCommentNewuser_;
    /**
     * <code>optional bool chat_comment_newuser = 202;</code>
     */
    public boolean getChatCommentNewuser() {
      return chatCommentNewuser_;
    }

    public static final int CHAT_COMMENT_BANUSER_FIELD_NUMBER = 203;
    private boolean chatCommentBanuser_;
    /**
     * <code>optional bool chat_comment_banuser = 203;</code>
     */
    public boolean getChatCommentBanuser() {
      return chatCommentBanuser_;
    }

    public static final int CHAT_COMMENT_LEAVEUSER_FIELD_NUMBER = 204;
    private boolean chatCommentLeaveuser_;
    /**
     * <code>optional bool chat_comment_leaveuser = 204;</code>
     */
    public boolean getChatCommentLeaveuser() {
      return chatCommentLeaveuser_;
    }

    public static final int CHAT_COMMENT_EDITS_CHANCE_FIELD_NUMBER = 205;
    private int chatCommentEditsChance_;
    /**
     * <code>optional int32 chat_comment_edits_chance = 205;</code>
     */
    public int getChatCommentEditsChance() {
      return chatCommentEditsChance_;
    }

    public static final int AUTOCONV_ENABLE_FIELD_NUMBER = 300;
    private boolean autoconvEnable_;
    /**
     * <code>optional bool autoconv_enable = 300;</code>
     */
    public boolean getAutoconvEnable() {
      return autoconvEnable_;
    }

    public static final int AUTOCONV_TIME_FIELD_NUMBER = 301;
    private boolean autoconvTime_;
    /**
     * <code>optional bool autoconv_time = 301;</code>
     */
    public boolean getAutoconvTime() {
      return autoconvTime_;
    }

    public static final int AUTOCONV_TEMPERATURE_FIELD_NUMBER = 302;
    private boolean autoconvTemperature_;
    /**
     * <code>optional bool autoconv_temperature = 302;</code>
     */
    public boolean getAutoconvTemperature() {
      return autoconvTemperature_;
    }

    public static final int AUTOCONV_LENGTH_FIELD_NUMBER = 303;
    private boolean autoconvLength_;
    /**
     * <code>optional bool autoconv_length = 303;</code>
     */
    public boolean getAutoconvLength() {
      return autoconvLength_;
    }

    public static final int AUTOCONV_AREA_FIELD_NUMBER = 304;
    private boolean autoconvArea_;
    /**
     * <code>optional bool autoconv_area = 304;</code>
     */
    public boolean getAutoconvArea() {
      return autoconvArea_;
    }

    public static final int AUTOCONV_VOLUME_FIELD_NUMBER = 305;
    private boolean autoconvVolume_;
    /**
     * <code>optional bool autoconv_volume = 305;</code>
     */
    public boolean getAutoconvVolume() {
      return autoconvVolume_;
    }

    public static final int AUTOCONV_MASS_FIELD_NUMBER = 306;
    private boolean autoconvMass_;
    /**
     * <code>optional bool autoconv_mass = 306;</code>
     */
    public boolean getAutoconvMass() {
      return autoconvMass_;
    }

    public static final int AUTOCONV_CURRENCY_FIELD_NUMBER = 307;
    private boolean autoconvCurrency_;
    /**
     * <code>optional bool autoconv_currency = 307;</code>
     */
    public boolean getAutoconvCurrency() {
      return autoconvCurrency_;
    }

    public static final int MISC_ADDEMOJI_FIELD_NUMBER = 400;
    private boolean miscAddemoji_;
    /**
     * <code>optional bool misc_addemoji = 400;</code>
     */
    public boolean getMiscAddemoji() {
      return miscAddemoji_;
    }

    public static final int MARKOV_EXLUDED_CHANNELS_FIELD_NUMBER = 500;
    private java.util.List<java.lang.Integer> markovExludedChannels_;
    /**
     * <code>repeated int32 markov_exluded_channels = 500;</code>
     */
    public java.util.List<java.lang.Integer>
        getMarkovExludedChannelsList() {
      return markovExludedChannels_;
    }
    /**
     * <code>repeated int32 markov_exluded_channels = 500;</code>
     */
    public int getMarkovExludedChannelsCount() {
      return markovExludedChannels_.size();
    }
    /**
     * <code>repeated int32 markov_exluded_channels = 500;</code>
     */
    public int getMarkovExludedChannels(int index) {
      return markovExludedChannels_.get(index);
    }
    private int markovExludedChannelsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (xpGain_ != false) {
        output.writeBool(100, xpGain_);
      }
      if (xpMsgMax_ != 0) {
        output.writeInt32(101, xpMsgMax_);
      }
      if (xpMsgMin_ != 0) {
        output.writeInt32(102, xpMsgMin_);
      }
      if (xpBombMax_ != 0) {
        output.writeInt32(103, xpBombMax_);
      }
      if (xpBombMin_ != 0) {
        output.writeInt32(104, xpBombMin_);
      }
      if (xpBombTimeoutMax_ != 0) {
        output.writeInt32(105, xpBombTimeoutMax_);
      }
      if (xpBombTimeoutMin_ != 0) {
        output.writeInt32(106, xpBombTimeoutMin_);
      }
      if (chatCommentEdits_ != false) {
        output.writeBool(200, chatCommentEdits_);
      }
      if (chatCommentBadwords_ != false) {
        output.writeBool(201, chatCommentBadwords_);
      }
      if (chatCommentNewuser_ != false) {
        output.writeBool(202, chatCommentNewuser_);
      }
      if (chatCommentBanuser_ != false) {
        output.writeBool(203, chatCommentBanuser_);
      }
      if (chatCommentLeaveuser_ != false) {
        output.writeBool(204, chatCommentLeaveuser_);
      }
      if (chatCommentEditsChance_ != 0) {
        output.writeInt32(205, chatCommentEditsChance_);
      }
      if (autoconvEnable_ != false) {
        output.writeBool(300, autoconvEnable_);
      }
      if (autoconvTime_ != false) {
        output.writeBool(301, autoconvTime_);
      }
      if (autoconvTemperature_ != false) {
        output.writeBool(302, autoconvTemperature_);
      }
      if (autoconvLength_ != false) {
        output.writeBool(303, autoconvLength_);
      }
      if (autoconvArea_ != false) {
        output.writeBool(304, autoconvArea_);
      }
      if (autoconvVolume_ != false) {
        output.writeBool(305, autoconvVolume_);
      }
      if (autoconvMass_ != false) {
        output.writeBool(306, autoconvMass_);
      }
      if (autoconvCurrency_ != false) {
        output.writeBool(307, autoconvCurrency_);
      }
      if (miscAddemoji_ != false) {
        output.writeBool(400, miscAddemoji_);
      }
      if (getMarkovExludedChannelsList().size() > 0) {
        output.writeUInt32NoTag(4002);
        output.writeUInt32NoTag(markovExludedChannelsMemoizedSerializedSize);
      }
      for (int i = 0; i < markovExludedChannels_.size(); i++) {
        output.writeInt32NoTag(markovExludedChannels_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (xpGain_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(100, xpGain_);
      }
      if (xpMsgMax_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(101, xpMsgMax_);
      }
      if (xpMsgMin_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(102, xpMsgMin_);
      }
      if (xpBombMax_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(103, xpBombMax_);
      }
      if (xpBombMin_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(104, xpBombMin_);
      }
      if (xpBombTimeoutMax_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(105, xpBombTimeoutMax_);
      }
      if (xpBombTimeoutMin_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(106, xpBombTimeoutMin_);
      }
      if (chatCommentEdits_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(200, chatCommentEdits_);
      }
      if (chatCommentBadwords_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(201, chatCommentBadwords_);
      }
      if (chatCommentNewuser_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(202, chatCommentNewuser_);
      }
      if (chatCommentBanuser_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(203, chatCommentBanuser_);
      }
      if (chatCommentLeaveuser_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(204, chatCommentLeaveuser_);
      }
      if (chatCommentEditsChance_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(205, chatCommentEditsChance_);
      }
      if (autoconvEnable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(300, autoconvEnable_);
      }
      if (autoconvTime_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(301, autoconvTime_);
      }
      if (autoconvTemperature_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(302, autoconvTemperature_);
      }
      if (autoconvLength_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(303, autoconvLength_);
      }
      if (autoconvArea_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(304, autoconvArea_);
      }
      if (autoconvVolume_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(305, autoconvVolume_);
      }
      if (autoconvMass_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(306, autoconvMass_);
      }
      if (autoconvCurrency_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(307, autoconvCurrency_);
      }
      if (miscAddemoji_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(400, miscAddemoji_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < markovExludedChannels_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(markovExludedChannels_.get(i));
        }
        size += dataSize;
        if (!getMarkovExludedChannelsList().isEmpty()) {
          size += 2;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        markovExludedChannelsMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.cyborgnoodle.Settings.Setting)) {
        return super.equals(obj);
      }
      io.github.cyborgnoodle.Settings.Setting other = (io.github.cyborgnoodle.Settings.Setting) obj;

      boolean result = true;
      result = result && (getXpGain()
          == other.getXpGain());
      result = result && (getXpMsgMax()
          == other.getXpMsgMax());
      result = result && (getXpMsgMin()
          == other.getXpMsgMin());
      result = result && (getXpBombMax()
          == other.getXpBombMax());
      result = result && (getXpBombMin()
          == other.getXpBombMin());
      result = result && (getXpBombTimeoutMax()
          == other.getXpBombTimeoutMax());
      result = result && (getXpBombTimeoutMin()
          == other.getXpBombTimeoutMin());
      result = result && (getChatCommentEdits()
          == other.getChatCommentEdits());
      result = result && (getChatCommentBadwords()
          == other.getChatCommentBadwords());
      result = result && (getChatCommentNewuser()
          == other.getChatCommentNewuser());
      result = result && (getChatCommentBanuser()
          == other.getChatCommentBanuser());
      result = result && (getChatCommentLeaveuser()
          == other.getChatCommentLeaveuser());
      result = result && (getChatCommentEditsChance()
          == other.getChatCommentEditsChance());
      result = result && (getAutoconvEnable()
          == other.getAutoconvEnable());
      result = result && (getAutoconvTime()
          == other.getAutoconvTime());
      result = result && (getAutoconvTemperature()
          == other.getAutoconvTemperature());
      result = result && (getAutoconvLength()
          == other.getAutoconvLength());
      result = result && (getAutoconvArea()
          == other.getAutoconvArea());
      result = result && (getAutoconvVolume()
          == other.getAutoconvVolume());
      result = result && (getAutoconvMass()
          == other.getAutoconvMass());
      result = result && (getAutoconvCurrency()
          == other.getAutoconvCurrency());
      result = result && (getMiscAddemoji()
          == other.getMiscAddemoji());
      result = result && getMarkovExludedChannelsList()
          .equals(other.getMarkovExludedChannelsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + XP_GAIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getXpGain());
      hash = (37 * hash) + XP_MSG_MAX_FIELD_NUMBER;
      hash = (53 * hash) + getXpMsgMax();
      hash = (37 * hash) + XP_MSG_MIN_FIELD_NUMBER;
      hash = (53 * hash) + getXpMsgMin();
      hash = (37 * hash) + XP_BOMB_MAX_FIELD_NUMBER;
      hash = (53 * hash) + getXpBombMax();
      hash = (37 * hash) + XP_BOMB_MIN_FIELD_NUMBER;
      hash = (53 * hash) + getXpBombMin();
      hash = (37 * hash) + XP_BOMB_TIMEOUT_MAX_FIELD_NUMBER;
      hash = (53 * hash) + getXpBombTimeoutMax();
      hash = (37 * hash) + XP_BOMB_TIMEOUT_MIN_FIELD_NUMBER;
      hash = (53 * hash) + getXpBombTimeoutMin();
      hash = (37 * hash) + CHAT_COMMENT_EDITS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getChatCommentEdits());
      hash = (37 * hash) + CHAT_COMMENT_BADWORDS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getChatCommentBadwords());
      hash = (37 * hash) + CHAT_COMMENT_NEWUSER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getChatCommentNewuser());
      hash = (37 * hash) + CHAT_COMMENT_BANUSER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getChatCommentBanuser());
      hash = (37 * hash) + CHAT_COMMENT_LEAVEUSER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getChatCommentLeaveuser());
      hash = (37 * hash) + CHAT_COMMENT_EDITS_CHANCE_FIELD_NUMBER;
      hash = (53 * hash) + getChatCommentEditsChance();
      hash = (37 * hash) + AUTOCONV_ENABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAutoconvEnable());
      hash = (37 * hash) + AUTOCONV_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAutoconvTime());
      hash = (37 * hash) + AUTOCONV_TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAutoconvTemperature());
      hash = (37 * hash) + AUTOCONV_LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAutoconvLength());
      hash = (37 * hash) + AUTOCONV_AREA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAutoconvArea());
      hash = (37 * hash) + AUTOCONV_VOLUME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAutoconvVolume());
      hash = (37 * hash) + AUTOCONV_MASS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAutoconvMass());
      hash = (37 * hash) + AUTOCONV_CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAutoconvCurrency());
      hash = (37 * hash) + MISC_ADDEMOJI_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMiscAddemoji());
      if (getMarkovExludedChannelsCount() > 0) {
        hash = (37 * hash) + MARKOV_EXLUDED_CHANNELS_FIELD_NUMBER;
        hash = (53 * hash) + getMarkovExludedChannelsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.cyborgnoodle.Settings.Setting parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.cyborgnoodle.Settings.Setting parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.cyborgnoodle.Settings.Setting parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.cyborgnoodle.Settings.Setting parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.cyborgnoodle.Settings.Setting parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.cyborgnoodle.Settings.Setting parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.cyborgnoodle.Settings.Setting parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.cyborgnoodle.Settings.Setting parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.cyborgnoodle.Settings.Setting parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.cyborgnoodle.Settings.Setting parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.cyborgnoodle.Settings.Setting prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Setting}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Setting)
        io.github.cyborgnoodle.Settings.SettingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.cyborgnoodle.Settings.internal_static_Setting_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.cyborgnoodle.Settings.internal_static_Setting_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.cyborgnoodle.Settings.Setting.class, io.github.cyborgnoodle.Settings.Setting.Builder.class);
      }

      // Construct using io.github.cyborgnoodle.Settings.Setting.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        xpGain_ = false;

        xpMsgMax_ = 0;

        xpMsgMin_ = 0;

        xpBombMax_ = 0;

        xpBombMin_ = 0;

        xpBombTimeoutMax_ = 0;

        xpBombTimeoutMin_ = 0;

        chatCommentEdits_ = false;

        chatCommentBadwords_ = false;

        chatCommentNewuser_ = false;

        chatCommentBanuser_ = false;

        chatCommentLeaveuser_ = false;

        chatCommentEditsChance_ = 0;

        autoconvEnable_ = false;

        autoconvTime_ = false;

        autoconvTemperature_ = false;

        autoconvLength_ = false;

        autoconvArea_ = false;

        autoconvVolume_ = false;

        autoconvMass_ = false;

        autoconvCurrency_ = false;

        miscAddemoji_ = false;

        markovExludedChannels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00400000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.cyborgnoodle.Settings.internal_static_Setting_descriptor;
      }

      public io.github.cyborgnoodle.Settings.Setting getDefaultInstanceForType() {
        return io.github.cyborgnoodle.Settings.Setting.getDefaultInstance();
      }

      public io.github.cyborgnoodle.Settings.Setting build() {
        io.github.cyborgnoodle.Settings.Setting result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.github.cyborgnoodle.Settings.Setting buildPartial() {
        io.github.cyborgnoodle.Settings.Setting result = new io.github.cyborgnoodle.Settings.Setting(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.xpGain_ = xpGain_;
        result.xpMsgMax_ = xpMsgMax_;
        result.xpMsgMin_ = xpMsgMin_;
        result.xpBombMax_ = xpBombMax_;
        result.xpBombMin_ = xpBombMin_;
        result.xpBombTimeoutMax_ = xpBombTimeoutMax_;
        result.xpBombTimeoutMin_ = xpBombTimeoutMin_;
        result.chatCommentEdits_ = chatCommentEdits_;
        result.chatCommentBadwords_ = chatCommentBadwords_;
        result.chatCommentNewuser_ = chatCommentNewuser_;
        result.chatCommentBanuser_ = chatCommentBanuser_;
        result.chatCommentLeaveuser_ = chatCommentLeaveuser_;
        result.chatCommentEditsChance_ = chatCommentEditsChance_;
        result.autoconvEnable_ = autoconvEnable_;
        result.autoconvTime_ = autoconvTime_;
        result.autoconvTemperature_ = autoconvTemperature_;
        result.autoconvLength_ = autoconvLength_;
        result.autoconvArea_ = autoconvArea_;
        result.autoconvVolume_ = autoconvVolume_;
        result.autoconvMass_ = autoconvMass_;
        result.autoconvCurrency_ = autoconvCurrency_;
        result.miscAddemoji_ = miscAddemoji_;
        if (((bitField0_ & 0x00400000) == 0x00400000)) {
          markovExludedChannels_ = java.util.Collections.unmodifiableList(markovExludedChannels_);
          bitField0_ = (bitField0_ & ~0x00400000);
        }
        result.markovExludedChannels_ = markovExludedChannels_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.cyborgnoodle.Settings.Setting) {
          return mergeFrom((io.github.cyborgnoodle.Settings.Setting)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.cyborgnoodle.Settings.Setting other) {
        if (other == io.github.cyborgnoodle.Settings.Setting.getDefaultInstance()) return this;
        if (other.getXpGain() != false) {
          setXpGain(other.getXpGain());
        }
        if (other.getXpMsgMax() != 0) {
          setXpMsgMax(other.getXpMsgMax());
        }
        if (other.getXpMsgMin() != 0) {
          setXpMsgMin(other.getXpMsgMin());
        }
        if (other.getXpBombMax() != 0) {
          setXpBombMax(other.getXpBombMax());
        }
        if (other.getXpBombMin() != 0) {
          setXpBombMin(other.getXpBombMin());
        }
        if (other.getXpBombTimeoutMax() != 0) {
          setXpBombTimeoutMax(other.getXpBombTimeoutMax());
        }
        if (other.getXpBombTimeoutMin() != 0) {
          setXpBombTimeoutMin(other.getXpBombTimeoutMin());
        }
        if (other.getChatCommentEdits() != false) {
          setChatCommentEdits(other.getChatCommentEdits());
        }
        if (other.getChatCommentBadwords() != false) {
          setChatCommentBadwords(other.getChatCommentBadwords());
        }
        if (other.getChatCommentNewuser() != false) {
          setChatCommentNewuser(other.getChatCommentNewuser());
        }
        if (other.getChatCommentBanuser() != false) {
          setChatCommentBanuser(other.getChatCommentBanuser());
        }
        if (other.getChatCommentLeaveuser() != false) {
          setChatCommentLeaveuser(other.getChatCommentLeaveuser());
        }
        if (other.getChatCommentEditsChance() != 0) {
          setChatCommentEditsChance(other.getChatCommentEditsChance());
        }
        if (other.getAutoconvEnable() != false) {
          setAutoconvEnable(other.getAutoconvEnable());
        }
        if (other.getAutoconvTime() != false) {
          setAutoconvTime(other.getAutoconvTime());
        }
        if (other.getAutoconvTemperature() != false) {
          setAutoconvTemperature(other.getAutoconvTemperature());
        }
        if (other.getAutoconvLength() != false) {
          setAutoconvLength(other.getAutoconvLength());
        }
        if (other.getAutoconvArea() != false) {
          setAutoconvArea(other.getAutoconvArea());
        }
        if (other.getAutoconvVolume() != false) {
          setAutoconvVolume(other.getAutoconvVolume());
        }
        if (other.getAutoconvMass() != false) {
          setAutoconvMass(other.getAutoconvMass());
        }
        if (other.getAutoconvCurrency() != false) {
          setAutoconvCurrency(other.getAutoconvCurrency());
        }
        if (other.getMiscAddemoji() != false) {
          setMiscAddemoji(other.getMiscAddemoji());
        }
        if (!other.markovExludedChannels_.isEmpty()) {
          if (markovExludedChannels_.isEmpty()) {
            markovExludedChannels_ = other.markovExludedChannels_;
            bitField0_ = (bitField0_ & ~0x00400000);
          } else {
            ensureMarkovExludedChannelsIsMutable();
            markovExludedChannels_.addAll(other.markovExludedChannels_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.cyborgnoodle.Settings.Setting parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.cyborgnoodle.Settings.Setting) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean xpGain_ ;
      /**
       * <code>optional bool xp_gain = 100;</code>
       */
      public boolean getXpGain() {
        return xpGain_;
      }
      /**
       * <code>optional bool xp_gain = 100;</code>
       */
      public Builder setXpGain(boolean value) {
        
        xpGain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool xp_gain = 100;</code>
       */
      public Builder clearXpGain() {
        
        xpGain_ = false;
        onChanged();
        return this;
      }

      private int xpMsgMax_ ;
      /**
       * <code>optional int32 xp_msg_max = 101;</code>
       */
      public int getXpMsgMax() {
        return xpMsgMax_;
      }
      /**
       * <code>optional int32 xp_msg_max = 101;</code>
       */
      public Builder setXpMsgMax(int value) {
        
        xpMsgMax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 xp_msg_max = 101;</code>
       */
      public Builder clearXpMsgMax() {
        
        xpMsgMax_ = 0;
        onChanged();
        return this;
      }

      private int xpMsgMin_ ;
      /**
       * <code>optional int32 xp_msg_min = 102;</code>
       */
      public int getXpMsgMin() {
        return xpMsgMin_;
      }
      /**
       * <code>optional int32 xp_msg_min = 102;</code>
       */
      public Builder setXpMsgMin(int value) {
        
        xpMsgMin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 xp_msg_min = 102;</code>
       */
      public Builder clearXpMsgMin() {
        
        xpMsgMin_ = 0;
        onChanged();
        return this;
      }

      private int xpBombMax_ ;
      /**
       * <code>optional int32 xp_bomb_max = 103;</code>
       */
      public int getXpBombMax() {
        return xpBombMax_;
      }
      /**
       * <code>optional int32 xp_bomb_max = 103;</code>
       */
      public Builder setXpBombMax(int value) {
        
        xpBombMax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 xp_bomb_max = 103;</code>
       */
      public Builder clearXpBombMax() {
        
        xpBombMax_ = 0;
        onChanged();
        return this;
      }

      private int xpBombMin_ ;
      /**
       * <code>optional int32 xp_bomb_min = 104;</code>
       */
      public int getXpBombMin() {
        return xpBombMin_;
      }
      /**
       * <code>optional int32 xp_bomb_min = 104;</code>
       */
      public Builder setXpBombMin(int value) {
        
        xpBombMin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 xp_bomb_min = 104;</code>
       */
      public Builder clearXpBombMin() {
        
        xpBombMin_ = 0;
        onChanged();
        return this;
      }

      private int xpBombTimeoutMax_ ;
      /**
       * <code>optional int32 xp_bomb_timeout_max = 105;</code>
       */
      public int getXpBombTimeoutMax() {
        return xpBombTimeoutMax_;
      }
      /**
       * <code>optional int32 xp_bomb_timeout_max = 105;</code>
       */
      public Builder setXpBombTimeoutMax(int value) {
        
        xpBombTimeoutMax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 xp_bomb_timeout_max = 105;</code>
       */
      public Builder clearXpBombTimeoutMax() {
        
        xpBombTimeoutMax_ = 0;
        onChanged();
        return this;
      }

      private int xpBombTimeoutMin_ ;
      /**
       * <code>optional int32 xp_bomb_timeout_min = 106;</code>
       */
      public int getXpBombTimeoutMin() {
        return xpBombTimeoutMin_;
      }
      /**
       * <code>optional int32 xp_bomb_timeout_min = 106;</code>
       */
      public Builder setXpBombTimeoutMin(int value) {
        
        xpBombTimeoutMin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 xp_bomb_timeout_min = 106;</code>
       */
      public Builder clearXpBombTimeoutMin() {
        
        xpBombTimeoutMin_ = 0;
        onChanged();
        return this;
      }

      private boolean chatCommentEdits_ ;
      /**
       * <code>optional bool chat_comment_edits = 200;</code>
       */
      public boolean getChatCommentEdits() {
        return chatCommentEdits_;
      }
      /**
       * <code>optional bool chat_comment_edits = 200;</code>
       */
      public Builder setChatCommentEdits(boolean value) {
        
        chatCommentEdits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool chat_comment_edits = 200;</code>
       */
      public Builder clearChatCommentEdits() {
        
        chatCommentEdits_ = false;
        onChanged();
        return this;
      }

      private boolean chatCommentBadwords_ ;
      /**
       * <code>optional bool chat_comment_badwords = 201;</code>
       */
      public boolean getChatCommentBadwords() {
        return chatCommentBadwords_;
      }
      /**
       * <code>optional bool chat_comment_badwords = 201;</code>
       */
      public Builder setChatCommentBadwords(boolean value) {
        
        chatCommentBadwords_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool chat_comment_badwords = 201;</code>
       */
      public Builder clearChatCommentBadwords() {
        
        chatCommentBadwords_ = false;
        onChanged();
        return this;
      }

      private boolean chatCommentNewuser_ ;
      /**
       * <code>optional bool chat_comment_newuser = 202;</code>
       */
      public boolean getChatCommentNewuser() {
        return chatCommentNewuser_;
      }
      /**
       * <code>optional bool chat_comment_newuser = 202;</code>
       */
      public Builder setChatCommentNewuser(boolean value) {
        
        chatCommentNewuser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool chat_comment_newuser = 202;</code>
       */
      public Builder clearChatCommentNewuser() {
        
        chatCommentNewuser_ = false;
        onChanged();
        return this;
      }

      private boolean chatCommentBanuser_ ;
      /**
       * <code>optional bool chat_comment_banuser = 203;</code>
       */
      public boolean getChatCommentBanuser() {
        return chatCommentBanuser_;
      }
      /**
       * <code>optional bool chat_comment_banuser = 203;</code>
       */
      public Builder setChatCommentBanuser(boolean value) {
        
        chatCommentBanuser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool chat_comment_banuser = 203;</code>
       */
      public Builder clearChatCommentBanuser() {
        
        chatCommentBanuser_ = false;
        onChanged();
        return this;
      }

      private boolean chatCommentLeaveuser_ ;
      /**
       * <code>optional bool chat_comment_leaveuser = 204;</code>
       */
      public boolean getChatCommentLeaveuser() {
        return chatCommentLeaveuser_;
      }
      /**
       * <code>optional bool chat_comment_leaveuser = 204;</code>
       */
      public Builder setChatCommentLeaveuser(boolean value) {
        
        chatCommentLeaveuser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool chat_comment_leaveuser = 204;</code>
       */
      public Builder clearChatCommentLeaveuser() {
        
        chatCommentLeaveuser_ = false;
        onChanged();
        return this;
      }

      private int chatCommentEditsChance_ ;
      /**
       * <code>optional int32 chat_comment_edits_chance = 205;</code>
       */
      public int getChatCommentEditsChance() {
        return chatCommentEditsChance_;
      }
      /**
       * <code>optional int32 chat_comment_edits_chance = 205;</code>
       */
      public Builder setChatCommentEditsChance(int value) {
        
        chatCommentEditsChance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 chat_comment_edits_chance = 205;</code>
       */
      public Builder clearChatCommentEditsChance() {
        
        chatCommentEditsChance_ = 0;
        onChanged();
        return this;
      }

      private boolean autoconvEnable_ ;
      /**
       * <code>optional bool autoconv_enable = 300;</code>
       */
      public boolean getAutoconvEnable() {
        return autoconvEnable_;
      }
      /**
       * <code>optional bool autoconv_enable = 300;</code>
       */
      public Builder setAutoconvEnable(boolean value) {
        
        autoconvEnable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool autoconv_enable = 300;</code>
       */
      public Builder clearAutoconvEnable() {
        
        autoconvEnable_ = false;
        onChanged();
        return this;
      }

      private boolean autoconvTime_ ;
      /**
       * <code>optional bool autoconv_time = 301;</code>
       */
      public boolean getAutoconvTime() {
        return autoconvTime_;
      }
      /**
       * <code>optional bool autoconv_time = 301;</code>
       */
      public Builder setAutoconvTime(boolean value) {
        
        autoconvTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool autoconv_time = 301;</code>
       */
      public Builder clearAutoconvTime() {
        
        autoconvTime_ = false;
        onChanged();
        return this;
      }

      private boolean autoconvTemperature_ ;
      /**
       * <code>optional bool autoconv_temperature = 302;</code>
       */
      public boolean getAutoconvTemperature() {
        return autoconvTemperature_;
      }
      /**
       * <code>optional bool autoconv_temperature = 302;</code>
       */
      public Builder setAutoconvTemperature(boolean value) {
        
        autoconvTemperature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool autoconv_temperature = 302;</code>
       */
      public Builder clearAutoconvTemperature() {
        
        autoconvTemperature_ = false;
        onChanged();
        return this;
      }

      private boolean autoconvLength_ ;
      /**
       * <code>optional bool autoconv_length = 303;</code>
       */
      public boolean getAutoconvLength() {
        return autoconvLength_;
      }
      /**
       * <code>optional bool autoconv_length = 303;</code>
       */
      public Builder setAutoconvLength(boolean value) {
        
        autoconvLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool autoconv_length = 303;</code>
       */
      public Builder clearAutoconvLength() {
        
        autoconvLength_ = false;
        onChanged();
        return this;
      }

      private boolean autoconvArea_ ;
      /**
       * <code>optional bool autoconv_area = 304;</code>
       */
      public boolean getAutoconvArea() {
        return autoconvArea_;
      }
      /**
       * <code>optional bool autoconv_area = 304;</code>
       */
      public Builder setAutoconvArea(boolean value) {
        
        autoconvArea_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool autoconv_area = 304;</code>
       */
      public Builder clearAutoconvArea() {
        
        autoconvArea_ = false;
        onChanged();
        return this;
      }

      private boolean autoconvVolume_ ;
      /**
       * <code>optional bool autoconv_volume = 305;</code>
       */
      public boolean getAutoconvVolume() {
        return autoconvVolume_;
      }
      /**
       * <code>optional bool autoconv_volume = 305;</code>
       */
      public Builder setAutoconvVolume(boolean value) {
        
        autoconvVolume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool autoconv_volume = 305;</code>
       */
      public Builder clearAutoconvVolume() {
        
        autoconvVolume_ = false;
        onChanged();
        return this;
      }

      private boolean autoconvMass_ ;
      /**
       * <code>optional bool autoconv_mass = 306;</code>
       */
      public boolean getAutoconvMass() {
        return autoconvMass_;
      }
      /**
       * <code>optional bool autoconv_mass = 306;</code>
       */
      public Builder setAutoconvMass(boolean value) {
        
        autoconvMass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool autoconv_mass = 306;</code>
       */
      public Builder clearAutoconvMass() {
        
        autoconvMass_ = false;
        onChanged();
        return this;
      }

      private boolean autoconvCurrency_ ;
      /**
       * <code>optional bool autoconv_currency = 307;</code>
       */
      public boolean getAutoconvCurrency() {
        return autoconvCurrency_;
      }
      /**
       * <code>optional bool autoconv_currency = 307;</code>
       */
      public Builder setAutoconvCurrency(boolean value) {
        
        autoconvCurrency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool autoconv_currency = 307;</code>
       */
      public Builder clearAutoconvCurrency() {
        
        autoconvCurrency_ = false;
        onChanged();
        return this;
      }

      private boolean miscAddemoji_ ;
      /**
       * <code>optional bool misc_addemoji = 400;</code>
       */
      public boolean getMiscAddemoji() {
        return miscAddemoji_;
      }
      /**
       * <code>optional bool misc_addemoji = 400;</code>
       */
      public Builder setMiscAddemoji(boolean value) {
        
        miscAddemoji_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool misc_addemoji = 400;</code>
       */
      public Builder clearMiscAddemoji() {
        
        miscAddemoji_ = false;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> markovExludedChannels_ = java.util.Collections.emptyList();
      private void ensureMarkovExludedChannelsIsMutable() {
        if (!((bitField0_ & 0x00400000) == 0x00400000)) {
          markovExludedChannels_ = new java.util.ArrayList<java.lang.Integer>(markovExludedChannels_);
          bitField0_ |= 0x00400000;
         }
      }
      /**
       * <code>repeated int32 markov_exluded_channels = 500;</code>
       */
      public java.util.List<java.lang.Integer>
          getMarkovExludedChannelsList() {
        return java.util.Collections.unmodifiableList(markovExludedChannels_);
      }
      /**
       * <code>repeated int32 markov_exluded_channels = 500;</code>
       */
      public int getMarkovExludedChannelsCount() {
        return markovExludedChannels_.size();
      }
      /**
       * <code>repeated int32 markov_exluded_channels = 500;</code>
       */
      public int getMarkovExludedChannels(int index) {
        return markovExludedChannels_.get(index);
      }
      /**
       * <code>repeated int32 markov_exluded_channels = 500;</code>
       */
      public Builder setMarkovExludedChannels(
          int index, int value) {
        ensureMarkovExludedChannelsIsMutable();
        markovExludedChannels_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 markov_exluded_channels = 500;</code>
       */
      public Builder addMarkovExludedChannels(int value) {
        ensureMarkovExludedChannelsIsMutable();
        markovExludedChannels_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 markov_exluded_channels = 500;</code>
       */
      public Builder addAllMarkovExludedChannels(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureMarkovExludedChannelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, markovExludedChannels_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 markov_exluded_channels = 500;</code>
       */
      public Builder clearMarkovExludedChannels() {
        markovExludedChannels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00400000);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Setting)
    }

    // @@protoc_insertion_point(class_scope:Setting)
    private static final io.github.cyborgnoodle.Settings.Setting DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.cyborgnoodle.Settings.Setting();
    }

    public static io.github.cyborgnoodle.Settings.Setting getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Setting>
        PARSER = new com.google.protobuf.AbstractParser<Setting>() {
      public Setting parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Setting(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Setting> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Setting> getParserForType() {
      return PARSER;
    }

    public io.github.cyborgnoodle.Settings.Setting getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Setting_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Setting_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016settings.proto\"\361\004\n\007Setting\022\017\n\007xp_gain\030" +
      "d \001(\010\022\022\n\nxp_msg_max\030e \001(\005\022\022\n\nxp_msg_min\030" +
      "f \001(\005\022\023\n\013xp_bomb_max\030g \001(\005\022\023\n\013xp_bomb_mi" +
      "n\030h \001(\005\022\033\n\023xp_bomb_timeout_max\030i \001(\005\022\033\n\023" +
      "xp_bomb_timeout_min\030j \001(\005\022\033\n\022chat_commen" +
      "t_edits\030\310\001 \001(\010\022\036\n\025chat_comment_badwords\030" +
      "\311\001 \001(\010\022\035\n\024chat_comment_newuser\030\312\001 \001(\010\022\035\n" +
      "\024chat_comment_banuser\030\313\001 \001(\010\022\037\n\026chat_com" +
      "ment_leaveuser\030\314\001 \001(\010\022\"\n\031chat_comment_ed" +
      "its_chance\030\315\001 \001(\005\022\030\n\017autoconv_enable\030\254\002 ",
      "\001(\010\022\026\n\rautoconv_time\030\255\002 \001(\010\022\035\n\024autoconv_" +
      "temperature\030\256\002 \001(\010\022\030\n\017autoconv_length\030\257\002" +
      " \001(\010\022\026\n\rautoconv_area\030\260\002 \001(\010\022\030\n\017autoconv" +
      "_volume\030\261\002 \001(\010\022\026\n\rautoconv_mass\030\262\002 \001(\010\022\032" +
      "\n\021autoconv_currency\030\263\002 \001(\010\022\026\n\rmisc_addem" +
      "oji\030\220\003 \001(\010\022 \n\027markov_exluded_channels\030\364\003" +
      " \003(\005B\030\n\026io.github.cyborgnoodleb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Setting_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Setting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Setting_descriptor,
        new java.lang.String[] { "XpGain", "XpMsgMax", "XpMsgMin", "XpBombMax", "XpBombMin", "XpBombTimeoutMax", "XpBombTimeoutMin", "ChatCommentEdits", "ChatCommentBadwords", "ChatCommentNewuser", "ChatCommentBanuser", "ChatCommentLeaveuser", "ChatCommentEditsChance", "AutoconvEnable", "AutoconvTime", "AutoconvTemperature", "AutoconvLength", "AutoconvArea", "AutoconvVolume", "AutoconvMass", "AutoconvCurrency", "MiscAddemoji", "MarkovExludedChannels", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
